## Indian Premier League (IPL) Regression Analysis

In [1]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# As usual, we begin by loading the packages we will need

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

In [3]:
# Now we load the data

IPL=pd.read_excel("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 1 - Foundations of Sports Analytics: Data, Representation, and Models in Sports/Week 5 Content/Week 5 Assignment/IPL (assignment) data.xlsx")

In [4]:
IPL

,year,team,played,won,lost,noresult,points,netrunrate,champions,runnersup,third,fourth,salaries
0,2008,Chennai Super Kings,14,8,6,0,16,-0.192,0,1,0,0,5825000
1,2009,Chennai Super Kings,14,8,5,1,17,0.951,0,0,0,0,6765000
2,2010,Chennai Super Kings,14,7,7,0,14,0.274,1,0,0,0,4890000
3,2011,Chennai Super Kings,14,9,5,0,18,0.443,1,0,0,0,6330000
4,2012,Chennai Super Kings,16,8,7,1,17,0.100,0,1,0,0,7900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2014,Sunrisers Hyderabad,14,6,8,0,12,-0.399,0,0,0,0,9803333
88,2015,Sunrisers Hyderabad,14,7,7,0,14,-0.239,0,0,0,0,8104667
89,2016,Sunrisers Hyderabad,14,8,6,0,16,0.245,1,0,0,0,8747666
90,2017,Sunrisers Hyderabad,14,8,5,1,17,0.599,0,0,0,1,8200500
91,2018,Sunrisers Hyderabad,14,9,5,0,18,0.284,0,1,0,0,10101580

In [5]:
# Create the sum of salaries in each season
Sumsal = IPL.groupby(['year'])['salaries'].sum().reset_index().rename(columns={'salaries':'allsal'})
Sumsal

    year    allsal
0   2008  34105000
1   2009  33445000
2   2010  33075000
3   2011  62210000
4   2012  59706250
5   2013  81535000
6   2014  73973332
7   2015  65242665
8   2016  63483666
9   2017  63014833
10  2018  84370160

In [6]:
# Merge the two dataframes on year
IPL = pd.merge(IPL, Sumsal, on=['year'], how='left')
display(IPL)

,year,team,played,won,lost,noresult,points,netrunrate,champions,runnersup,third,fourth,salaries,allsal
0,2008,Chennai Super Kings,14,8,6,0,16,-0.192,0,1,0,0,5825000,34105000
1,2009,Chennai Super Kings,14,8,5,1,17,0.951,0,0,0,0,6765000,33445000
2,2010,Chennai Super Kings,14,7,7,0,14,0.274,1,0,0,0,4890000,33075000
3,2011,Chennai Super Kings,14,9,5,0,18,0.443,1,0,0,0,6330000,62210000
4,2012,Chennai Super Kings,16,8,7,1,17,0.100,0,1,0,0,7900000,59706250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2014,Sunrisers Hyderabad,14,6,8,0,12,-0.399,0,0,0,0,9803333,73973332
88,2015,Sunrisers Hyderabad,14,7,7,0,14,-0.239,0,0,0,0,8104667,65242665
89,2016,Sunrisers Hyderabad,14,8,6,0,16,0.245,1,0,0,0,8747666,63483666
90,2017,Sunrisers Hyderabad,14,8,5,1,17,0.599,0,0,0,1,8200500,63014833
91,2018,Sunrisers Hyderabad,14,9,5,0,18,0.284,0,1,0,0,10101580,84370160

In [7]:
# Create a variable for team salary divided by total salaries for that season (relsal).
IPL['relsal']= IPL['salaries']/IPL['allsal']

In [8]:
# Creating a value for win percentage. Defined as wins divided by games with a result (= games played minus games with no result).
IPL['win_pct']=IPL['won'] / (IPL['played']-IPL['noresult'])

In [9]:
# Taking another look at our dataframe with our newly created variables.
IPL

,year,team,played,won,lost,noresult,points,netrunrate,champions,runnersup,third,fourth,salaries,allsal,relsal,win_pct
0,2008,Chennai Super Kings,14,8,6,0,16,-0.192,0,1,0,0,5825000,34105000,0.170796,0.571429
1,2009,Chennai Super Kings,14,8,5,1,17,0.951,0,0,0,0,6765000,33445000,0.202272,0.615385
2,2010,Chennai Super Kings,14,7,7,0,14,0.274,1,0,0,0,4890000,33075000,0.147846,0.500000
3,2011,Chennai Super Kings,14,9,5,0,18,0.443,1,0,0,0,6330000,62210000,0.101752,0.642857
4,2012,Chennai Super Kings,16,8,7,1,17,0.100,0,1,0,0,7900000,59706250,0.132314,0.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2014,Sunrisers Hyderabad,14,6,8,0,12,-0.399,0,0,0,0,9803333,73973332,0.132525,0.428571
88,2015,Sunrisers Hyderabad,14,7,7,0,14,-0.239,0,0,0,0,8104667,65242665,0.124223,0.500000
89,2016,Sunrisers Hyderabad,14,8,6,0,16,0.245,1,0,0,0,8747666,63483666,0.137794,0.571429
90,2017,Sunrisers Hyderabad,14,8,5,1,17,0.599,0,0,0,1,8200500,63014833,0.130136,0.615385
91,2018,Sunrisers Hyderabad,14,9,5,0,18,0.284,0,1,0,0,10101580,84370160,0.119729,0.642857

In [10]:
# first we sort the values
IPL.sort_values(by=['team','year'], ascending=True)

,year,team,played,won,lost,noresult,points,netrunrate,champions,runnersup,third,fourth,salaries,allsal,relsal,win_pct
0,2008,Chennai Super Kings,14,8,6,0,16,-0.192,0,1,0,0,5825000,34105000,0.170796,0.571429
1,2009,Chennai Super Kings,14,8,5,1,17,0.951,0,0,0,0,6765000,33445000,0.202272,0.615385
2,2010,Chennai Super Kings,14,7,7,0,14,0.274,1,0,0,0,4890000,33075000,0.147846,0.500000
3,2011,Chennai Super Kings,14,9,5,0,18,0.443,1,0,0,0,6330000,62210000,0.101752,0.642857
4,2012,Chennai Super Kings,16,8,7,1,17,0.100,0,1,0,0,7900000,59706250,0.132314,0.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2014,Sunrisers Hyderabad,14,6,8,0,12,-0.399,0,0,0,0,9803333,73973332,0.132525,0.428571
88,2015,Sunrisers Hyderabad,14,7,7,0,14,-0.239,0,0,0,0,8104667,65242665,0.124223,0.500000
89,2016,Sunrisers Hyderabad,14,8,6,0,16,0.245,1,0,0,0,8747666,63483666,0.137794,0.571429
90,2017,Sunrisers Hyderabad,14,8,5,1,17,0.599,0,0,0,1,8200500,63014833,0.130136,0.615385
91,2018,Sunrisers Hyderabad,14,9,5,0,18,0.284,0,1,0,0,10101580,84370160,0.119729,0.642857

In [11]:
# now we create the lagged dependend variable
IPL['wpc_lag'] = IPL.groupby('team')['win_pct'].shift(1)
IPL

,year,team,played,won,lost,noresult,points,netrunrate,champions,runnersup,third,fourth,salaries,allsal,relsal,win_pct,wpc_lag
0,2008,Chennai Super Kings,14,8,6,0,16,-0.192,0,1,0,0,5825000,34105000,0.170796,0.571429,NaN
1,2009,Chennai Super Kings,14,8,5,1,17,0.951,0,0,0,0,6765000,33445000,0.202272,0.615385,0.571429
2,2010,Chennai Super Kings,14,7,7,0,14,0.274,1,0,0,0,4890000,33075000,0.147846,0.500000,0.615385
3,2011,Chennai Super Kings,14,9,5,0,18,0.443,1,0,0,0,6330000,62210000,0.101752,0.642857,0.500000
4,2012,Chennai Super Kings,16,8,7,1,17,0.100,0,1,0,0,7900000,59706250,0.132314,0.533333,0.642857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2014,Sunrisers Hyderabad,14,6,8,0,12,-0.399,0,0,0,0,9803333,73973332,0.132525,0.428571,0.625000
88,2015,Sunrisers Hyderabad,14,7,7,0,14,-0.239,0,0,0,0,8104667,65242665,0.124223,0.500000,0.428571
89,2016,Sunrisers Hyderabad,14,8,6,0,16,0.245,1,0,0,0,8747666,63483666,0.137794,0.571429,0.500000
90,2017,Sunrisers Hyderabad,14,8,5,1,17,0.599,0,0,0,1,8200500,63014833,0.130136,0.615385,0.571429
91,2018,Sunrisers Hyderabad,14,9,5,0,18,0.284,0,1,0,0,10101580,84370160,0.119729,0.642857,0.615385

In [12]:
# Regression of win_pct on relsal
lm_1 = smf.ols(formula = 'win_pct ~ relsal', data=IPL).fit()
print(lm_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                win_pct   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.009
Method:                 Least Squares   F-statistic:                    0.1622
Date:                Tue, 04 Aug 2026   Prob (F-statistic):              0.688
Time:                        18:12:09   Log-Likelihood:                 45.259
No. Observations:                  92   AIC:                            -86.52
Df Residuals:                      90   BIC:                            -81.47
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4752      0.063      7.563      0.000       0.350       0.600
relsal         0.2050      0.509      0.403      0.688      -0.806       1.216
==============================================================================
Omnibus:                        3.778   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.151   Jarque-Bera (JB):                3.780
Skew:                          -0.474   Prob(JB):                        0.151
Kurtosis:                       2.703   Cond. No.                         33.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

From the above regression we can see this model is not very good.  We have a R-squared of 0.002 saying that our regression explains 0.2 percent of variation in our data.  We also see that our only dependent variable of relsal has a p-value way higher than 0.05 meaning that it is not significant in our regression.  Next we will try to add the lagged win percentage to this model to see if we can get a stronger outcome.

In [13]:
# Regression of win_pct on relsal and wpc_lag
lm_2 = smf.ols(formula = 'win_pct ~ relsal+wpc_lag', data=IPL).fit()
print(lm_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                win_pct   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     1.591
Date:                Tue, 04 Aug 2026   Prob (F-statistic):              0.210
Time:                        18:17:04   Log-Likelihood:                 43.314
No. Observations:                  79   AIC:                            -80.63
Df Residuals:                      76   BIC:                            -73.52
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.3489      0.087      4.003      0.000       0.175       0.522
relsal         0.6785      0.523      1.297      0.198      -0.363       1.720
wpc_lag        0.1406      0.108      1.300      0.198      -0.075       0.356
==============================================================================
Omnibus:                        3.816   Durbin-Watson:                   1.827
Prob(Omnibus):                  0.148   Jarque-Bera (JB):                3.581
Skew:                          -0.520   Prob(JB):                        0.167
Kurtosis:                       2.926   Cond. No.                         37.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

This regression is a little better but still not very good and we fall in to a couple of the same problems.  Firstly, our R-squared is 0.040 meaning our regression exlpains about 4 percent of variation in our data which we would like to be much higher.  Lastly, again, both of our dependent variables have a p-value substantially higher than 0.05 meaning they aare not significant.  Now let's try one final regression adding in the fixed effects for each team.

In [14]:
# Regression of win_pct on relsal, wpc_lag, and team fixed effects
lm_3 = smf.ols(formula = 'win_pct ~ relsal+wpc_lag+C(team)', data=IPL).fit()
print(lm_3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                win_pct   R-squared:                       0.297
Model:                            OLS   Adj. R-squared:                  0.157
Method:                 Least Squares   F-statistic:                     2.117
Date:                Tue, 04 Aug 2026   Prob (F-statistic):             0.0245
Time:                        18:22:18   Log-Likelihood:                 55.639
No. Observations:                  79   AIC:                            -83.28
Df Residuals:                      65   BIC:                            -50.10
Df Model:                          13
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.6665      0.138      4.826      0.000       0.391       0.942
C(team)[T.Deccan Chargers]                -0.1857      0.085     -2.187      0.032      -0.355      -0.016
C(team)[T.Delhi Daredevils]               -0.2059      0.069     -2.972      0.004      -0.344      -0.068
C(team)[T.Gujarat Lions]                  -0.3294      0.143     -2.310      0.024      -0.614      -0.045
C(team)[T.Kings XI Punjab]                -0.1747      0.069     -2.547      0.013      -0.312      -0.038
C(team)[T.Kochi Tuskers Kerala]         3.608e-16   5.92e-16      0.610      0.544   -8.21e-16    1.54e-15
C(team)[T.Kolkata Knight Riders]          -0.0972      0.065     -1.495      0.140      -0.227       0.033
C(team)[T.Mumbai Indians]                 -0.0405      0.065     -0.622      0.536      -0.170       0.090
C(team)[T.Pune Warriors India]            -0.3893      0.118     -3.301      0.002      -0.625      -0.154
C(team)[T.Rajasthan Royals]               -0.1259      0.086     -1.471      0.146      -0.297       0.045
C(team)[T.Rising Pune Supergiants]         0.0118      0.144      0.082      0.935      -0.275       0.299
C(team)[T.Royal Challengers Bangalore]    -0.1175      0.064     -1.838      0.071      -0.245       0.010
C(team)[T.Sunrisers Hyderabad]            -0.0669      0.076     -0.877      0.384      -0.219       0.086
relsal                                    -0.1014      0.690     -0.147      0.884      -1.478       1.276
wpc_lag                                   -0.0636      0.115     -0.554      0.582      -0.293       0.166
==============================================================================
Omnibus:                        2.352   Durbin-Watson:                   2.188
Prob(Omnibus):                  0.308   Jarque-Bera (JB):                1.775
Skew:                          -0.153   Prob(JB):                        0.412
Kurtosis:                       3.668   Cond. No.                     1.34e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.08e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

This regression shows big improvements over our first two models.  Our R-squared for this regression sits at 0.297 stating that this regression explains 29.7 percent of variation in the data which we would still like to be higher but is a huge increase over our other models.  We can also see that about half of the team fixed effects are significant while the other half along with wpc_lag and relsal again are not significant.

####**Conclusion:**

After doing this lab and running all three regressions we can conclude that cricket, and the IPL in particular, seems to be the only league we studied where relsal and lagged win percentage both seem to have no significant effect on win percentage.  Being that our model is still not as good as we would hope for, since it only explains about 30 percent of variability in our data, a next step could be adding more different dependent variables along with some interactions to see if we can get a better model in terms of R-squared.  Doing this would also allow us to get a clearer picture to if relsal and lagged win percentage will ever be significant values in a regression or if they just don't matter as much as they do in other sports leagues to increase win percentage.