## Part 1 - Import and Explore Data

In [1]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#Import Libraries
import pandas as pd
import numpy as np
import datetime
import statsmodels.formula.api as sm

In [3]:
#Import NFL_Game dataset
NFL_Game=pd.read_csv("/content/drive/MyDrive/Sports Performance Analytics Michigan/Course 1 - Foundations of Sports Analytics: Data, Representation, and Models in Sports/Week 4 Content/Week 4 Assignment/nfl_game.csv")
display(NFL_Game)

,game_id,stadium,date,score,weather_temperature,weather_wind_mph,weather_humidity,score_diff,home,win,...,stadium_close,stadium_type,stadium_age,conference,division,season,team_division,team_division_pre2002,team,stadium_neutral
0,1,Orange Bowl,9/2/1966,14,83,6,71,-9,1,0,...,2008.0,outdoor,29,NFC,NFC West,1966,AFC East,AFC East,Miami Dolphins,0
1,1,Orange Bowl,9/2/1966,23,83,6,71,9,0,1,...,2008.0,outdoor,29,AFC,AFC Central,1966,AFC West,AFC West,Oakland Raiders,0
2,2,Rice Stadium,9/3/1966,45,81,7,70,38,1,1,...,NaN,outdoor,16,NFC,NFC West,1966,NaN,AFC Central,Houston Oilers,0
3,2,Rice Stadium,9/3/1966,7,81,7,70,-38,0,0,...,NaN,outdoor,16,NFC,NFC West,1966,AFC West,AFC West,Denver Broncos,0
4,3,Balboa Stadium,9/4/1966,27,70,7,82,20,1,1,...,NaN,outdoor,52,NFC,NFC West,1966,AFC West,AFC West,San Diego Chargers,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24309,12155,MetLife Stadium,12/29/2019,17,42,5,69,-17,1,0,...,NaN,outdoor,9,NFC,NFC East,2019,NFC East,NFC East,New York Giants,0
24310,12156,CenturyLink Field,12/29/2019,26,51,3,70,5,0,1,...,NaN,outdoor,17,AFC,AFC West,2019,NFC West,NFC West,San Francisco 49ers,0
24311,12156,CenturyLink Field,12/29/2019,21,51,3,70,-5,1,0,...,NaN,outdoor,17,AFC,AFC West,2019,NFC West,AFC West,Seattle Seahawks,0
24312,12157,Raymond James Stadium,12/29/2019,28,78,12,77,6,0,1,...,2016.0,outdoor,21,NFC,AFC East,2019,NFC South,NFC West,Atlanta Falcons,0
24313,12157,Raymond James Stadium,12/29/2019,22,78,12,77,-6,1,0,...,2016.0,outdoor,21,AFC,AFC West,2019,NFC South,NFC Central,Tampa Bay Buccaneers,0

In [4]:
# Calculate summary statistics for the date variable
NFL_Game['date'].describe()

count          24314
unique          2065
top       12/29/2019
freq              32
Name: date, dtype: object

From our summary statistics we can see that there are 24,314 dates in the column, there are 2065 uniques dates in the column, the top date was 12/29/2019 and it showed up 32 times in the column.

In [5]:
# Calculate summary statistics for score variable based on if the game was home or away
NFL_Game.groupby('home')['score'].describe()

        count       mean        std  min   25%   50%   75%   max
home
0     12157.0  19.643004  10.166614  0.0  13.0  20.0  27.0  62.0
1     12157.0  22.254997  10.533005  0.0  14.0  21.0  29.0  72.0

From these statistics we can see that there are the same number of home and away games.  The mean score for a home team was 22.25 and the mean score for an away team was 19.643.  The home team scores range from 0 to 72 with a median at 21 and the away team scores range from 0 to 62 with a median at 20.

Let's check a few correlation coefficients before getting into the regression.

In [6]:
# Correlation coefficient between win and home
NFL_Game['win'].corr(NFL_Game['home'])

np.float64(0.14790211753177582)

In [7]:
# Correlation coefficient between score_diff and home
NFL_Game['score_diff'].corr(NFL_Game['home'])

np.float64(0.1725059685987271)

In [8]:
# Correlation coefficient between score and weather_temperature
NFL_Game['score'].corr(NFL_Game['weather_temperature'])

np.float64(0.03361690080893199)

In [9]:
# Correlation coefficient between score and weather_humidity
NFL_Game['score'].corr(NFL_Game['weather_humidity'])

np.float64(-0.03278832087607435)

In [10]:
# Correlation coefficient between score and weather_wind_mph
NFL_Game['score'].corr(NFL_Game['weather_wind_mph'])

np.float64(-0.07895602955806046)

## Part 2 - Regression Analysis 1 - Test of Home Game Advantage

In this regression analysis, you will try to determine if playing at home gives teams any advantage in their performance.

Run the following regressions where the variable “score_diff” is the dependent variable.

In [11]:
# Regression of score_diff on home
Reg1_1 = sm.ols(formula = 'score_diff ~ home', data= NFL_Game).fit()
print(Reg1_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             score_diff   R-squared:                       0.030
Model:                            OLS   Adj. R-squared:                  0.030
Method:                 Least Squares   F-statistic:                     745.7
Date:                Fri, 31 Jul 2026   Prob (F-statistic):          9.64e-162
Time:                        17:33:57   Log-Likelihood:            -1.0020e+05
No. Observations:               24314   AIC:                         2.004e+05
Df Residuals:                   24312   BIC:                         2.004e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.6120      0.135    -19.309      0.000      -2.877      -2.347
home           5.2240      0.191     27.307      0.000       4.849       5.599
==============================================================================
Omnibus:                       29.538   Durbin-Watson:                   3.021
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.843
Skew:                          -0.000   Prob(JB):                     2.72e-08
Kurtosis:                       3.185   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Our regression tells us that if a team is home the score diff will increase by 5.22.  We also have a high t-value and p-value less than 0.05 indicating that this is statistically significant.  The R-Squared however is only 0.030 indicating that our regression only captures about 3 percent of variation in the data.  We can definitely get a better model which we will try to do with the second regression.

In [ ]:
# Regression of score_diff on home, stadium_capacity, stadium_neutral, and the interaction between home and stadium neutral
Reg1_2 = sm.ols(formula = 'score_diff ~ home+stadium_capacity+stadium_neutral+home*stadium_neutral', data= NFL_Game).fit()
print(Reg1_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             score_diff   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.030
Method:                 Least Squares   F-statistic:                     191.7
Date:                Tue, 28 Jul 2026   Prob (F-statistic):          3.99e-162
Time:                        21:52:27   Log-Likelihood:            -1.0019e+05
No. Observations:               24314   AIC:                         2.004e+05
Df Residuals:                   24309   BIC:                         2.004e+05
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               -2.6386      0.695     -3.796      0.000      -4.001      -1.276
home                     5.2765      0.192     27.542      0.000       4.901       5.652
stadium_capacity      5.195e-09   9.91e-06      0.001      1.000   -1.94e-05    1.94e-05
stadium_neutral          7.2518      2.253      3.218      0.001       2.835      11.669
home:stadium_neutral   -14.5038      3.185     -4.554      0.000     -20.746      -8.262
==============================================================================
Omnibus:                       30.413   Durbin-Watson:                   3.021
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               35.975
Skew:                           0.000   Prob(JB):                     1.54e-08
Kurtosis:                       3.188   Cond. No.                     2.65e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.65e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

Our regression tells us

*   If a team is home the score diff will increase by 5.28.
*   If the stadium capacity increases by one the score diff will increase by 0.0000000052
*   If a game is at a neutral site the score diff will increase by 7.25.
*   If the team is a home team and the game is played at a neutral site the score diff will be 5.2765-14.5038 = -9.2273 meaning it will decrease by 9.2273


We also have high t-value and p-value less than 0.05 for all variables except stadium capacity indicating that all the interactions are statistically significant except for stadium capacity. The R-Squared only increases 0.031 indicating that our regression only captures about 3.1 percent of variation in the data. This is better than our first model by a slim margin but maybe our last model of this type can get us a better interpretation of the data.

In [12]:
# Regression of score_diff on home, stadium_capacity, stadium_neutral, the interaction between home and stadium neutral and the interaction between team and opponent.
Reg1_3 = sm.ols(formula = 'score_diff ~ home+stadium_capacity+stadium_neutral+home*stadium_neutral+team*opponent', data= NFL_Game).fit()
print(Reg1_3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             score_diff   R-squared:                       0.128
Model:                            OLS   Adj. R-squared:                  0.073
Method:                 Least Squares   F-statistic:                     2.321
Date:                Fri, 31 Jul 2026   Prob (F-statistic):          1.34e-137
Time:                        18:13:10   Log-Likelihood:                -98906.
No. Observations:               24314   AIC:                         2.007e+05
Df Residuals:                   22866   BIC:                         2.124e+05
Df Model:                        1447
Covariance Type:            nonrobust
=================================================================================================================================
                                                                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------
Intercept                                                        -2.7118      1.598     -1.697      0.090      -5.844       0.420
team[T.Atlanta Falcons]                                           8.9218      3.910      2.282      0.023       1.257      16.586
team[T.Baltimore Colts]                                           6.5544      1.521      4.310      0.000       3.574       9.535
team[T.Baltimore Ravens]                                          1.7530      5.524      0.317      0.751      -9.074      12.580
team[T.Boston Patriots]                                          -8.5357      3.080     -2.771      0.006     -14.573      -2.499
team[T.Buffalo Bills]                                             6.1404      6.475      0.948      0.343      -6.552      18.833
team[T.Carolina Panthers]                                         4.9977      4.032      1.240      0.215      -2.904      12.900
team[T.Chicago Bears]                                            -0.2563      4.914     -0.052      0.958      -9.887       9.375
team[T.Cincinnati Bengals]                                       -2.8055      5.188     -0.541      0.589     -12.975       7.364
team[T.Cleveland Browns]                                          3.9568      5.527      0.716      0.474      -6.877      14.790
team[T.Dallas Cowboys]                                           10.6434      3.147      3.382      0.001       4.475      16.812
team[T.Denver Broncos]                                           18.3853      5.527      3.327      0.001       7.553      29.218
team[T.Detroit Lions]                                            -2.0341      3.611     -0.563      0.573      -9.111       5.043
team[T.Green Bay Packers]                                         8.4977      5.189      1.638      0.102      -1.674      18.669
team[T.Houston Oilers]                                          -20.7154     14.277     -1.451      0.147     -48.700       7.269
team[T.Houston Texans]                                            2.7478      7.221      0.381      0.704     -11.407      16.902
team[T.Indianapolis Colts]                                       -0.5448      6.482     -0.084      0.933     -13.250      12.161
team[T.Jacksonville Jaguars]                                      1.6551      6.478      0.256      0.798     -11.041      14.351
team[T.Kansas City Chiefs]                                       12.7477      5.193      2.455      0.014       2.569      22.926
team[T.Los Angeles Chargers]                                     32.2850     14.327      2.253      0.024       4.203      60.366
team[T.Los Angeles Raiders]                                       4.9346      1.769      2.789      0.005       1.466       8.403
team[T.Los Angeles Rams]                                         12.2850      4.928      2.493      0.013       2.625      21.945
team[T.Miami Dolphins]                                            1.4978      5.938      0.252      0.801     -10.141      13.136
team[T.Minnesota Vikings]                                         6.2836      3.904      1.610      0.107      -1.368      13.935
team[T.New England Patriots]                                     17.6644      5.939      2.975      0.003       6.025      29.304
team[T.New Orleans Saints]                                        2.6080      4.490      0.581      0.561      -6.193      11.409
team[T.New York Giants]                                           2.3462      3.148      0.745      0.456      -3.824       8.517
team[T.New York Jets]                                             3.6643      5.939      0.617      0.537      -7.976      15.305
team[T.Oakland Raiders]                                           3.8140      5.523      0.691      0.490      -7.011      14.639
team[T.Philadelphia Eagles]                                       2.5922      3.149      0.823      0.410      -3.580       8.765
team[T.Phoenix Cardinals]                                        -2.0799      2.292     -0.907      0.364      -6.572       2.412
team[T.Pittsburgh Steelers]                                       6.7320      5.523      1.219      0.223      -4.093      17.557
team[T.San Diego Chargers]                                        5.6101      5.527      1.015      0.310      -5.222      16.443
team[T.San Francisco 49ers]                                       2.0689      2.679      0.772      0.440      -3.182       7.319
team[T.Seattle Seahawks]                                          6.5504      2.676      2.447      0.014       1.305      11.796
team[T.St. Louis Cardinals]                                       4.8399      1.688      2.868      0.004       1.532       8.148
team[T.St. Louis Rams]                                           -4.6022      2.936     -1.568      0.117     -10.356       1.152
team[T.Tampa Bay Buccaneers]                                     -3.7008      4.917     -0.753      0.452     -13.339       5.938
team[T.Tennessee Oilers]                                         29.7110     14.416      2.061      0.039       1.454      57.968
team[T.Tennessee Titans]                                         -3.7522      7.221     -0.520      0.603     -17.907      10.402
team[T.Washington Redskins]                                       4.4092      3.147      1.401      0.161      -1.760      10.578
opponent[T.Atlanta Falcons]                                      -8.9263      3.910     -2.283      0.022     -16.591      -1.262
opponent[T.Baltimore Colts]                                      -6.5545      1.521     -4.310      0.000      -9.535      -3.574
opponent[T.Baltimore Ravens]                                     -1.7575      5.524     -0.318      0.750     -12.584       9.069
opponent[T.Boston Patriots]                                       8.5355      3.080      2.771      0.006       2.499      14.572
opponent[T.Buffalo Bills]                                        -6.1449      6.475     -0.949      0.343     -18.837       6.547
opponent[T.Carolina Panthers]                                    -5.0023      4.032     -1.241      0.215     -12.904       2.900
opponent[T.Chicago Bears]                                         0.2519      4.914      0.051      0.959      -9.379       9.883
opponent[T.Cincinnati Bengals]                                    2.8011      5.188      0.540      0.589      -7.368      12.970
opponent[T.Cleveland Browns]                                     -3.9613      5.527     -0.717      0.474     -14.795       6.872
opponent[T.Dallas Cowboys]                                      -10.6478      3.147     -3.384      0.001     -16.816      -4.480
opponent[T.Denver Broncos]                                      -18.3899      5.527     -3.328      0.001     -29.222      -7.557
opponent[T.Detroit Lions]                                         2.0296      3.611      0.562      0.574      -5.048       9.107
opponent[T.Green Bay Packers]                                    -8.5023      5.189     -1.638      0.101     -18.674       1.669
opponent[T.Houston Oilers]                                       20.7111     14.277      1.451      0.147      -7.274      48.696
opponent[T.Houston Texans]                                       -2.7522      7.221     -0.381      0.703     -16.907      11.402
opponent[T.Indianapolis Colts]                                    0.5405      6.482      0.083      0.934     -12.165      13.246
opponent[T.Jacksonville Jaguars]                                 -1.6596      6.478     -0.256      0.798     -14.356      11.037
opponent[T.Kansas City Chiefs]                                  -12.7523      5.193     -2.456      0.014     -22.931      -2.574
opponent[T.Los Angeles Chargers]                                -32.2885     14.327     -2.254      0.024     -60.370      -4.207
opponent[T.Los Angeles Raiders]                                  -4.9352      1.769     -2.789      0.005      -8.403      -1.467
opponent[T.Los Angeles Rams]                                    -12.2896      4.928     -2.494      0.013     -21.950      -2.629
opponent[T.Miami Dolphins]                                       -1.5022      5.938     -0.253      0.800     -13.141      10.136
opponent[T.Minnesota Vikings]                                    -6.2880      3.904     -1.611      0.107     -13.940       1.364
opponent[T.New England Patriots]                                -17.6689      5.939     -2.975      0.003     -29.309      -6.029
opponent[T.New Orleans Saints]                                   -2.6126      4.490     -0.582      0.561     -11.414       6.189
opponent[T.New York Giants]                                      -2.3509      3.148     -0.747      0.455      -8.521       3.819
opponent[T.New York Jets]                                        -3.6690      5.939     -0.618      0.537     -15.309       7.971
opponent[T.Oakland Raiders]                                      -3.8183      5.523     -0.691      0.489     -14.643       7.007
opponent[T.Philadelphia Eagles]                                  -2.5967      3.149     -0.825      0.410      -8.769       3.576
opponent[T.Phoenix Cardinals]                                     2.0796      2.292      0.907      0.364      -2.413       6.572
opponent[T.Pittsburgh Steelers]                                  -6.7365      5.523     -1.220      0.223     -17.561       4.088
opponent[T.San Diego Chargers]                                   -5.6147      5.527     -1.016      0.310     -16.447       5.218
opponent[T.San Francisco 49ers]                                  -2.0733      2.679     -0.774      0.439      -7.324       3.177
opponent[T.Seattle Seahawks]                                     -6.5549      2.676     -2.449      0.014     -11.801      -1.309
opponent[T.St. Louis Cardinals]                                  -4.8402      1.688     -2.868      0.004      -8.148      -1.532
opponent[T.St. Louis Rams]                                        4.5978      2.936      1.566      0.117      -1.156      10.352
opponent[T.Tampa Bay Buccaneers]                                  3.6963      4.917      0.752      0.452      -5.942      13.335
opponent[T.Tennessee Oilers]                                    -29.7156     14.416     -2.061      0.039     -57.972      -1.459
opponent[T.Tennessee Titans]                                      3.7478      7.221      0.519      0.604     -10.407      17.902
opponent[T.Washington Redskins]                                  -4.4138      3.147     -1.402      0.161     -10.583       1.755
team[T.Atlanta Falcons]:opponent[T.Atlanta Falcons]            7.719e-11    2.3e-10      0.336      0.737   -3.73e-10    5.27e-10
team[T.Baltimore Colts]:opponent[T.Atlanta Falcons]              20.1731      6.339      3.183      0.001       7.749      32.597
team[T.Baltimore Ravens]:opponent[T.Atlanta Falcons]             15.4087      8.904      1.731      0.084      -2.043      32.861
team[T.Boston Patriots]:opponent[T.Atlanta Falcons]            1.543e-10   9.52e-11      1.621      0.105   -3.23e-11    3.41e-10
team[T.Buffalo Bills]:opponent[T.Atlanta Falcons]                 1.3085      8.547      0.153      0.878     -15.444      18.061
team[T.Carolina Panthers]:opponent[T.Atlanta Falcons]             1.3062      5.822      0.224      0.822     -10.105      12.717
team[T.Chicago Bears]:opponent[T.Atlanta Falcons]                10.7466      6.738      1.595      0.111      -2.461      23.954
team[T.Cincinnati Bengals]:opponent[T.Atlanta Falcons]           14.2296      7.448      1.910      0.056      -0.369      28.829
team[T.Cleveland Browns]:opponent[T.Atlanta Falcons]             13.2530      7.622      1.739      0.082      -1.686      28.192
team[T.Dallas Cowboys]:opponent[T.Atlanta Falcons]                2.4894      5.609      0.444      0.657      -8.505      13.483
team[T.Denver Broncos]:opponent[T.Atlanta Falcons]               -6.3899      7.687     -0.831      0.406     -21.458       8.678
team[T.Detroit Lions]:opponent[T.Atlanta Falcons]                11.7611      5.672      2.073      0.038       0.643      22.879
team[T.Green Bay Packers]:opponent[T.Atlanta Falcons]             4.0596      6.884      0.590      0.555      -9.434      17.554
team[T.Houston Oilers]:opponent[T.Atlanta Falcons]               25.9410     15.518      1.672      0.095      -4.476      56.358
team[T.Houston Texans]:opponent[T.Atlanta Falcons]                4.6336     10.392      0.446      0.656     -15.735      25.002
team[T.Indianapolis Colts]:opponent[T.Atlanta Falcons]           14.3896      8.888      1.619      0.105      -3.031      31.810
team[T.Jacksonville Jaguars]:opponent[T.Atlanta Falcons]          4.6565      9.256      0.503      0.615     -13.485      22.799
team[T.Kansas City Chiefs]:opponent[T.Atlanta Falcons]            2.3666      7.996      0.296      0.767     -13.306      18.040
team[T.Los Angeles Chargers]:opponent[T.Atlanta Falcons]      -5.884e-10   6.97e-10     -0.844      0.399   -1.95e-09    7.78e-10
team[T.Los Angeles Raiders]:opponent[T.Atlanta Falcons]          11.9321      7.472      1.597      0.110      -2.714      26.578
team[T.Los Angeles Rams]:opponent[T.Atlanta Falcons]              3.5638      6.435      0.554      0.580      -9.049      16.176
team[T.Miami Dolphins]:opponent[T.Atlanta Falcons]                9.1078      8.061      1.130      0.259      -6.692      24.908
team[T.Minnesota Vikings]:opponent[T.Atlanta Falcons]            10.0445      5.997      1.675      0.094      -1.710      21.799
team[T.New England Patriots]:opponent[T.Atlanta Falcons]        -10.8528      7.989     -1.358      0.174     -26.512       4.806
team[T.New Orleans Saints]:opponent[T.Atlanta Falcons]            5.3161      5.972      0.890      0.373      -6.389      17.021
team[T.New York Giants]:opponent[T.Atlanta Falcons]               5.8872      5.670      1.038      0.299      -5.226      17.000
team[T.New York Jets]:opponent[T.Atlanta Falcons]                 6.9263      8.145      0.850      0.395      -9.039      22.892
team[T.Oakland Raiders]:opponent[T.Atlanta Falcons]               4.3642      8.214      0.531      0.595     -11.737      20.465
team[T.Philadelphia Eagles]:opponent[T.Atlanta Falcons]           9.2069      5.472      1.682      0.093      -1.519      19.933
team[T.Phoenix Cardinals]:opponent[T.Atlanta Falcons]            20.5465      7.586      2.709      0.007       5.678      35.415
team[T.Pittsburgh Steelers]:opponent[T.Atlanta Falcons]          13.6920      7.561      1.811      0.070      -1.128      28.512
team[T.San Diego Chargers]:opponent[T.Atlanta Falcons]           -5.5288      8.072     -0.685      0.493     -21.351      10.293
team[T.San Francisco 49ers]:opponent[T.Atlanta Falcons]          12.7365      4.830      2.637      0.008       3.269      22.204
team[T.Seattle Seahawks]:opponent[T.Atlanta Falcons]              5.3905      5.748      0.938      0.348      -5.877      16.658
team[T.St. Louis Cardinals]:opponent[T.Atlanta Falcons]           7.6424      5.840      1.309      0.191      -3.804      19.089
team[T.St. Louis Rams]:opponent[T.Atlanta Falcons]               19.9262      5.712      3.489      0.000       8.731      31.122
team[T.Tampa Bay Buccaneers]:opponent[T.Atlanta Falcons]         12.9429      6.448      2.007      0.045       0.304      25.582
team[T.Tennessee Oilers]:opponent[T.Atlanta Falcons]          -1.902e-10   9.53e-11     -1.996      0.046   -3.77e-10   -3.43e-12
team[T.Tennessee Titans]:opponent[T.Atlanta Falcons]             18.0096     10.046      1.793      0.073      -1.680      37.700
team[T.Washington Redskins]:opponent[T.Atlanta Falcons]           8.2064      5.640      1.455      0.146      -2.848      19.261
team[T.Atlanta Falcons]:opponent[T.Baltimore Colts]             -20.1727      6.339     -3.183      0.001     -32.597      -7.749
team[T.Baltimore Colts]:opponent[T.Baltimore Colts]           -2.672e-11   5.44e-11     -0.491      0.623   -1.33e-10    7.99e-11
team[T.Baltimore Ravens]:opponent[T.Baltimore Colts]          -3.393e-11   5.81e-10     -0.058      0.953   -1.17e-09     1.1e-09
team[T.Boston Patriots]:opponent[T.Baltimore Colts]              -0.9120      9.705     -0.094      0.925     -19.935      18.111
team[T.Buffalo Bills]:opponent[T.Baltimore Colts]                -1.2812      7.002     -0.183      0.855     -15.006      12.444
team[T.Carolina Panthers]:opponent[T.Baltimore Colts]          5.956e-10   3.14e-10      1.894      0.058   -2.08e-11    1.21e-09
team[T.Chicago Bears]:opponent[T.Baltimore Colts]                -2.1913      6.995     -0.313      0.754     -15.903      11.520
team[T.Cincinnati Bengals]:opponent[T.Baltimore Colts]           12.6612      7.188      1.761      0.078      -1.427      26.750
team[T.Cleveland Browns]:opponent[T.Baltimore Colts]             10.0080      7.242      1.382      0.167      -4.186      24.202
team[T.Dallas Cowboys]:opponent[T.Baltimore Colts]               12.0756      6.570      1.838      0.066      -0.802      24.953
team[T.Denver Broncos]:opponent[T.Baltimore Colts]               -3.3331      7.964     -0.419      0.676     -18.943      12.277
team[T.Detroit Lions]:opponent[T.Baltimore Colts]                -0.9135      6.163     -0.148      0.882     -12.994      11.167
team[T.Green Bay Packers]:opponent[T.Baltimore Colts]            -0.6421      7.188     -0.089      0.929     -14.731      13.447
team[T.Houston Oilers]:opponent[T.Baltimore Colts]               25.3389     15.245      1.662      0.097      -4.542      55.220
team[T.Houston Texans]:opponent[T.Baltimore Colts]             1.271e-10    7.2e-11      1.766      0.077    -1.4e-11    2.68e-10
team[T.Indianapolis Colts]:opponent[T.Baltimore Colts]        -6.223e-11   1.07e-10     -0.581      0.561   -2.72e-10    1.48e-10
team[T.Jacksonville Jaguars]:opponent[T.Baltimore Colts]      -3.747e-10   2.99e-10     -1.254      0.210    -9.6e-10    2.11e-10
team[T.Kansas City Chiefs]:opponent[T.Baltimore Colts]           -2.5704      7.188     -0.358      0.721     -16.659      11.518
team[T.Los Angeles Chargers]:opponent[T.Baltimore Colts]      -1.413e-10   1.77e-10     -0.798      0.425   -4.89e-10    2.06e-10
team[T.Los Angeles Raiders]:opponent[T.Baltimore Colts]        2.425e-10   3.27e-10      0.741      0.459   -3.99e-10    8.84e-10
team[T.Los Angeles Rams]:opponent[T.Baltimore Colts]             -4.7328      6.637     -0.713      0.476     -17.742       8.277
team[T.Miami Dolphins]:opponent[T.Baltimore Colts]               12.0902      6.497      1.861      0.063      -0.645      24.825
team[T.Minnesota Vikings]:opponent[T.Baltimore Colts]             1.6775      6.611      0.254      0.800     -11.281      14.636
team[T.New England Patriots]:opponent[T.Baltimore Colts]         -8.0435      6.562     -1.226      0.220     -20.906       4.818

This regression shows us the statistics for the variables explored in the last model but adds the interaction between every team and opponent which gives us a lot more variables.  Looking at the R-squared we can see it increased from the 0.031 we got in our last model to 0.128 meaning this model captures 12.8 percent of variation.  This model is about 4 times better than our last one.  Now we will explore the impact of outside factors on score.

## Part 3 - Regression Analysis 2 -- Impact of Outside Factors on Scores

In this regression analysis, you will investigate if the final score earned by each team is affected by outside factors such as the size and condition of the stadium as well as weather conditions at the stadium.

Run the following regressions where the variable “score” is the dependent variable.

In [13]:
# Regression of score on season and home
Reg2_1 = sm.ols(formula = 'score ~ season+home', data= NFL_Game).fit()
print(Reg2_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.022
Model:                            OLS   Adj. R-squared:                  0.022
Method:                 Least Squares   F-statistic:                     273.3
Date:                Fri, 31 Jul 2026   Prob (F-statistic):          4.37e-118
Time:                        18:35:19   Log-Likelihood:                -91246.
No. Observations:               24314   AIC:                         1.825e+05
Df Residuals:                   24311   BIC:                         1.825e+05
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -88.2969      8.615    -10.249      0.000    -105.183     -71.411
season         0.0541      0.004     12.530      0.000       0.046       0.063
home           2.6120      0.132     19.736      0.000       2.353       2.871
==============================================================================
Omnibus:                      480.134   Durbin-Watson:                   2.056
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              508.905
Skew:                           0.354   Prob(JB):                    3.11e-111
Kurtosis:                       2.992   Cond. No.                     2.60e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.6e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Our regression tells us that if a team is home their score will increase by 2.61 points. Also, as the season increases by one year the score will increase by 0.054 points.  We have a high t-value and p-value less than 0.05 indicating that these relationships are statistically significant. The R-Squared however is only 0.022 indicating that our regression only captures about 2.2 percent of variation in the data. We can definitely get a better model which we will try to do with the second regression.

In [14]:
# Regression of score on season, home, weather_temperature, weather_wind_mph, and weather_humidity
Reg2_2 = sm.ols(formula = 'score ~ season+home+weather_temperature+weather_wind_mph+weather_humidity', data= NFL_Game).fit()
print(Reg2_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.026
Model:                            OLS   Adj. R-squared:                  0.026
Method:                 Least Squares   F-statistic:                     129.9
Date:                Fri, 31 Jul 2026   Prob (F-statistic):          2.60e-136
Time:                        18:42:46   Log-Likelihood:                -91195.
No. Observations:               24314   AIC:                         1.824e+05
Df Residuals:                   24308   BIC:                         1.825e+05
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept             -58.1972      9.142     -6.366      0.000     -76.117     -40.277
season                  0.0400      0.005      8.797      0.000       0.031       0.049
home                    2.6120      0.132     19.776      0.000       2.353       2.871
weather_temperature    -0.0006      0.005     -0.127      0.899      -0.010       0.009
weather_wind_mph       -0.1188      0.013     -8.937      0.000      -0.145      -0.093
weather_humidity       -0.0150      0.004     -3.506      0.000      -0.023      -0.007
==============================================================================
Omnibus:                      482.730   Durbin-Watson:                   2.061
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              511.818
Skew:                           0.355   Prob(JB):                    7.25e-112
Kurtosis:                       2.992   Cond. No.                     2.76e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.76e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Our regression tells us that

*   If a team is home their score will increase by 2.61 points.
*   As the season increases by one year the score will increase by 0.04 points.
*   As the temperature increases by one degree score will decrease by 0.0006 points.
*   As the wind speed increases by one mph score will decrease by 0.1188 points.
*   As the humidity increases by one percent score will decrease by 0.015 points.

We have a high t-value and p-value less than 0.05 for all variables besides weather_temperature indicating that these relationships are all statistically significant except for temperature. The R-Squared however increases slightly to 0.026 indicating that our regression only captures about 2.6 percent of variation in the data. We will try to get a better model in our third regression.

In [15]:
# Regression of score on season, home, weather_temperature, weather_wind_mph, weather_humidity, stadium_capacity, stadium_age, stadium_type, stadium_neutral, and the interaction between home and stadium_neutral
Reg2_3 = sm.ols(formula = 'score ~ season+home+weather_temperature+weather_wind_mph+weather_humidity+stadium_capacity+stadium_age+stadium_type+stadium_neutral+home*stadium_neutral', data= NFL_Game).fit()
print(Reg2_3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.026
Method:                 Least Squares   F-statistic:                     60.80
Date:                Fri, 31 Jul 2026   Prob (F-statistic):          2.09e-134
Time:                        19:00:41   Log-Likelihood:                -91186.
No. Observations:               24314   AIC:                         1.824e+05
Df Residuals:                   24302   BIC:                         1.825e+05
Df Model:                          11
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                     -56.2290      9.412     -5.974      0.000     -74.677     -37.781
stadium_type[T.outdoor]         0.3262      0.246      1.329      0.184      -0.155       0.808
stadium_type[T.retractable]     0.5971      0.400      1.493      0.135      -0.187       1.381
season                          0.0393      0.005      8.295      0.000       0.030       0.049
home                            2.6382      0.132     19.944      0.000       2.379       2.898
weather_temperature             0.0009      0.005      0.183      0.855      -0.008       0.010
weather_wind_mph               -0.1329      0.017     -7.998      0.000      -0.166      -0.100
weather_humidity               -0.0144      0.004     -3.313      0.001      -0.023      -0.006
stadium_capacity            -1.237e-05   6.95e-06     -1.779      0.075    -2.6e-05    1.26e-06
stadium_age                     0.0053      0.004      1.370      0.171      -0.002       0.013
stadium_neutral                 3.8516      1.558      2.473      0.013       0.798       6.905
home:stadium_neutral           -7.2545      2.199     -3.299      0.001     -11.564      -2.945
==============================================================================
Omnibus:                      481.968   Durbin-Watson:                   2.061
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              510.964
Skew:                           0.355   Prob(JB):                    1.11e-111
Kurtosis:                       2.993   Cond. No.                     9.92e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.92e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

Our regression tells us that

*   If a team is home their score will increase by 2.64 points.
*   As the season increases by one year the score will increase by 0.039 points.
*   As the temperature increases by one degree score will decrease by 0.0009 points.
*   As the wind speed increases by one mph score will decrease by 0.1329 points.
*   As the humidity increases by one percent score will decrease by 0.0144 points.
*   If a team plays in an outdoor stadium their score will increase by 0.326 points.
*   If a team plays in a retractable stadium their score will increase by 0.597 points.
*   If the stadium increases by one person, the team's score will decrease by 0.0000124 points.
*   As the stadium age increases by one year, the team's score will increase by 0.0053 points.
*   If the team plays at a neutral site, their score will increase by 3.85 points
*   If the home team plays at a neutral site, their score decrease by (2.6382-7.2545 = -4.6163) 4.616 points.

We have a high t-value and p-value less than 0.05 for season, home, weather_wind_mph, weather_humidity, stadium_neutral, and home*stadium_neutral indicating that these relationships are all statistically significant where all other variables present are not statistically significant. The R-Squared again increases slightly from 0.26 to 0.27 indicating that our regression only captures about 2.7 percent of variation in the data. We will try one last time to get a better model in our final regression.

In [16]:
# Regression of score on season, home, weather_temperature, weather_wind_mph, weather_humidity, stadium_capacity, stadium_age, stadium_type, stadium_neutral, team, opponent and the interaction between home and stadium_neutral
Reg2_4 = sm.ols(formula = 'score ~ season+home+weather_temperature+weather_wind_mph+weather_humidity+stadium_capacity+stadium_age+stadium_type+stadium_neutral+home*stadium_neutral+team+opponent', data= NFL_Game).fit()
print(Reg2_4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.052
Model:                            OLS   Adj. R-squared:                  0.048
Method:                 Least Squares   F-statistic:                     14.52
Date:                Fri, 31 Jul 2026   Prob (F-statistic):          9.04e-211
Time:                        19:37:22   Log-Likelihood:                -90870.
No. Observations:               24314   AIC:                         1.819e+05
Df Residuals:                   24222   BIC:                         1.827e+05
Df Model:                          91
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Intercept                          -76.4276     10.760     -7.103      0.000     -97.518     -55.337
stadium_type[T.outdoor]              0.5037      0.282      1.788      0.074      -0.048       1.056
stadium_type[T.retractable]          0.9230      0.456      2.024      0.043       0.029       1.817
team[T.Atlanta Falcons]              1.8932      0.632      2.996      0.003       0.655       3.132
team[T.Baltimore Colts]              3.5594      0.834      4.267      0.000       1.924       5.194
team[T.Baltimore Ravens]             3.1741      0.742      4.280      0.000       1.721       4.628
team[T.Boston Patriots]             -0.8464      1.695     -0.499      0.618      -4.168       2.476
team[T.Buffalo Bills]                1.9598      0.639      3.066      0.002       0.707       3.213
team[T.Carolina Panthers]            1.7296      0.729      2.374      0.018       0.301       3.158
team[T.Chicago Bears]                0.6359      0.639      0.996      0.319      -0.616       1.888
team[T.Cincinnati Bengals]           2.9926      0.641      4.672      0.000       1.737       4.248
team[T.Cleveland Browns]             1.2596      0.643      1.959      0.050      -0.001       2.520
team[T.Dallas Cowboys]               4.8059      0.626      7.676      0.000       3.579       6.033
team[T.Denver Broncos]               3.9463      0.633      6.229      0.000       2.705       5.188
team[T.Detroit Lions]                1.9008      0.640      2.972      0.003       0.647       3.154
team[T.Green Bay Packers]            4.1008      0.638      6.423      0.000       2.849       5.352
team[T.Houston Oilers]               1.8725      0.722      2.592      0.010       0.457       3.289
team[T.Houston Texans]               1.3649      0.802      1.702      0.089      -0.207       2.937
team[T.Indianapolis Colts]           2.9074      0.675      4.308      0.000       1.585       4.230
team[T.Jacksonville Jaguars]         1.4175      0.736      1.927      0.054      -0.024       2.859
team[T.Kansas City Chiefs]           3.9458      0.636      6.203      0.000       2.699       5.193
team[T.Los Angeles Chargers]         3.7211      1.571      2.369      0.018       0.642       6.800
team[T.Los Angeles Raiders]          3.3321      0.905      3.681      0.000       1.558       5.106
team[T.Los Angeles Rams]             4.3044      0.701      6.143      0.000       2.931       5.678
team[T.Miami Dolphins]               3.2156      0.639      5.032      0.000       1.963       4.468
team[T.Minnesota Vikings]            3.8548      0.638      6.045      0.000       2.605       5.105
team[T.New England Patriots]         5.0600      0.644      7.862      0.000       3.799       6.321
team[T.New Orleans Saints]           2.7787      0.639      4.346      0.000       1.526       4.032
team[T.New York Giants]              2.2064      0.634      3.477      0.001       0.963       3.450
team[T.New York Jets]                2.4567      0.639      3.843      0.000       1.204       3.710
team[T.Oakland Raiders]              3.7209      0.667      5.577      0.000       2.413       5.029
team[T.Philadelphia Eagles]          3.0308      0.633      4.791      0.000       1.791       4.271
team[T.Phoenix Cardinals]           -0.9981      1.163     -0.858      0.391      -3.277       1.281
team[T.Pittsburgh Steelers]          3.6902      0.637      5.797      0.000       2.442       4.938
team[T.San Diego Chargers]           4.0198      0.641      6.270      0.000       2.763       5.276
team[T.San Francisco 49ers]          4.1713      0.631      6.610      0.000       2.934       5.408
team[T.Seattle Seahawks]             2.9875      0.653      4.575      0.000       1.708       4.267
team[T.St. Louis Cardinals]          3.4192      0.786      4.351      0.000       1.879       4.959
team[T.St. Louis Rams]               1.7163      0.767      2.237      0.025       0.213       3.220
team[T.Tampa Bay Buccaneers]        -0.1927      0.652     -0.296      0.768      -1.470       1.085
team[T.Tennessee Oilers]             2.6730      1.879      1.423      0.155      -1.010       6.356
team[T.Tennessee Titans]             2.4747      0.768      3.224      0.001       0.970       3.979
team[T.Washington Redskins]          3.0688      0.632      4.856      0.000       1.830       4.308
opponent[T.Atlanta Falcons]          0.4912      0.632      0.777      0.437      -0.747       1.730
opponent[T.Baltimore Colts]         -1.1805      0.834     -1.415      0.157      -2.815       0.454
opponent[T.Baltimore Ravens]        -3.8206      0.742     -5.152      0.000      -5.274      -2.367
opponent[T.Boston Patriots]          4.6224      1.695      2.727      0.006       1.300       7.944
opponent[T.Buffalo Bills]           -0.7378      0.639     -1.154      0.248      -1.991       0.515
opponent[T.Carolina Panthers]       -1.0991      0.729     -1.508      0.131      -2.527       0.329
opponent[T.Chicago Bears]           -2.5110      0.639     -3.932      0.000      -3.763      -1.259
opponent[T.Cincinnati Bengals]      -0.0347      0.641     -0.054      0.957      -1.290       1.221
opponent[T.Cleveland Browns]        -0.6110      0.643     -0.950      0.342      -1.871       0.649
opponent[T.Dallas Cowboys]          -2.4348      0.626     -3.889      0.000      -3.662      -1.208
opponent[T.Denver Broncos]          -1.8177      0.633     -2.869      0.004      -3.059      -0.576
opponent[T.Detroit Lions]           -0.2535      0.640     -0.396      0.692      -1.507       1.000
opponent[T.Green Bay Packers]       -1.4413      0.638     -2.257      0.024      -2.693      -0.190
opponent[T.Houston Oilers]          -0.3673      0.722     -0.508      0.611      -1.783       1.049
opponent[T.Houston Texans]          -0.5031      0.802     -0.627      0.530      -2.075       1.069
opponent[T.Indianapolis Colts]      -0.5140      0.675     -0.762      0.446      -1.837       0.809
opponent[T.Jacksonville Jaguars]    -1.0732      0.736     -1.459      0.145      -2.515       0.369
opponent[T.Kansas City Chiefs]      -2.0137      0.636     -3.166      0.002      -3.261      -0.767
opponent[T.Los Angeles Chargers]    -4.7459      1.571     -3.021      0.003      -7.825      -1.667
opponent[T.Los Angeles Raiders]     -2.5319      0.905     -2.797      0.005      -4.306      -0.758
opponent[T.Los Angeles Rams]        -2.5319      0.701     -3.614      0.000      -3.905      -1.159
opponent[T.Miami Dolphins]          -1.8728      0.639     -2.931      0.003      -3.125      -0.620
opponent[T.Minnesota Vikings]       -2.0035      0.638     -3.142      0.002      -3.253      -0.754
opponent[T.New England Patriots]    -1.6967      0.644     -2.636      0.008      -2.958      -0.435
opponent[T.New Orleans Saints]       0.4342      0.639      0.679      0.497      -0.819       1.687
opponent[T.New York Giants]         -0.8421      0.634     -1.327      0.184      -2.086       0.402
opponent[T.New York Jets]           -0.2666      0.639     -0.417      0.677      -1.520       0.987
opponent[T.Oakland Raiders]         -0.7677      0.667     -1.151      0.250      -2.076       0.540
opponent[T.Philadelphia Eagles]     -1.4977      0.633     -2.368      0.018      -2.738      -0.258
opponent[T.Phoenix Cardinals]       -0.3676      1.163     -0.316      0.752      -2.647       1.911
opponent[T.Pittsburgh Steelers]     -3.2290      0.637     -5.072      0.000      -4.477      -1.981
opponent[T.San Diego Chargers]      -0.5080      0.641     -0.792      0.428      -1.765       0.749
opponent[T.San Francisco 49ers]     -1.5695      0.631     -2.487      0.013      -2.806      -0.333
opponent[T.Seattle Seahawks]        -1.5430      0.653     -2.363      0.018      -2.823      -0.263
opponent[T.St. Louis Cardinals]      0.8117      0.786      1.033      0.302      -0.728       2.352
opponent[T.St. Louis Rams]           0.8396      0.767      1.094      0.274      -0.664       2.343
opponent[T.Tampa Bay Buccaneers]    -0.4812      0.652     -0.738      0.460      -1.759       0.797
opponent[T.Tennessee Oilers]        -2.8100      1.879     -1.495      0.135      -6.493       0.873
opponent[T.Tennessee Titans]        -0.4421      0.768     -0.576      0.565      -1.947       1.063
opponent[T.Washington Redskins]     -1.1894      0.632     -1.882      0.060      -2.428       0.049
season                               0.0484      0.005      9.012      0.000       0.038       0.059
home                                 2.6626      0.131     20.342      0.000       2.406       2.919
weather_temperature                  0.0020      0.005      0.402      0.688      -0.008       0.012
weather_wind_mph                    -0.1385      0.017     -8.205      0.000      -0.172      -0.105
weather_humidity                    -0.0142      0.004     -3.168      0.002      -0.023      -0.005
stadium_capacity                 -1.533e-05   8.18e-06     -1.874      0.061   -3.14e-05    7.05e-07
stadium_age                          0.0131      0.004      3.021      0.003       0.005       0.022
stadium_neutral                      3.6310      1.547      2.347      0.019       0.598       6.663
home:stadium_neutral                -6.7504      2.185     -3.090      0.002     -11.032      -2.469
==============================================================================
Omnibus:                      466.658   Durbin-Watson:                   2.050
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              493.763
Skew:                           0.349   Prob(JB):                    6.03e-108
Kurtosis:                       3.014   Cond. No.                     1.15e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.15e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

This regression shows us the statistics for the variables explored in the last model but adds the team and opponent which allows us to look at an increase or decrease in score based on which team is playing and who their opponent is. Looking at the R-squared we can see it increased from the 0.027 we got in our last model to 0.052 meaning this model captures 5.2 percent of variation. This model is about 2 times better than our last one.

In [20]:
NFL_Game['stadium_type'].value_counts()

stadium_type
outdoor        19510
indoor          3892
retractable      912
Name: count, dtype: int64